# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-27 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200727_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='\u6210\u90fd', max_length=100),
            preserve_default=False,
        ),
    ]
