# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_zhushitest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='describe',
        ),
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(default='\u6280\u672f\u7b14\u8bb0', max_length=100),
            preserve_default=False,
        ),
    ]
