# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_auto_20200826_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='contents',
            field=models.TextField(default='\u6211\u6240\u6709\u7684\u4e1c\u897f\u554a'),
            preserve_default=False,
        ),
    ]
