# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_homeindex_resumecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeindex',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homeindex',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=16),
            preserve_default=False,
        ),
    ]
