# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201112_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
